name: C Make

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt-get install -y libpam0g-dev
    - name: make
      run: make
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: lidm
        asset_name: lidm
        tag: ${{ github.ref }}
